development:
  adapter: postgresql
  encoding: utf8
  database: gpwanalizer
  username: postgres
  password: root
  host: 127.0.0.1
  port: 5432
  
test:
   adapter: postgresql
   database: maskrz_test
   host: pgsql-591378.vipserv.org
   username: maskrz_dev
   password: develo
   pool: 5
   timeout: 5000

production:
   adapter: postgresql
   database: maskrz_prod
   host: pgsql-591378.vipserv.org
   username: maskrz_dev
   password: develo
   pool: 5
   timeout: 5000
