development:
  adapter: mysql2
  encoding: utf8
  database: gpwanalizer
  username: root
  password:
  host: 127.0.0.1
  port: 3306

production:
   adapter: postgresql
   database: maskrz_prod
   host: pgsql-591378.vipserv.org
   username: maskrz_dev
   password: develo
   pool: 5
   timeout: 5000
   port: 5433
